#!/usr/bin/env python3
"""
export-pipeline.py
Export skill pipeline as Mermaid diagram.

Usage:
    python export-pipeline.py [--output <file.md>]

Outputs a Mermaid flowchart showing the skill development pipeline:
    skill-architect → skill-planner → skill-builder

Exit codes:
    0 - Success
    1 - Error
"""

import sys
from pathlib import Path
from datetime import datetime


def generate_pipeline_diagram() -> str:
    """Generate the Master Skill Suite Pipeline diagram in Mermaid format."""

    diagram = """# Master Skill Suite Pipeline

> Generated by skill-architect v2.0
> Date: {date}

```mermaid
flowchart LR
    subgraph MasterPipeline [🎯 Master Skill Suite Pipeline]
        direction LR

        subgraph Stage1 [Stage 1: Design]
            A1[skill-architect<br/>Architect]
            A2[design.md]
        end

        subgraph Stage2 [Stage 2: Plan]
            P1[skill-planner<br/>Planner]
            P2[todo.md]
        end

        subgraph Stage3 [Stage 3: Build]
            B1[skill-builder<br/>Builder]
            B2[Skill Files]
        end

        A1 -->|creates| A2
        A2 -->|input| P1
        P1 -->|creates| P2
        P2 -->|input| B1
        B1 -->|generates| B2

        User -.->|Requirements| A1
        B2 -.->|Deliver| User

        style A1 fill:#ffcdd2,stroke:#e53935,stroke-width:2px
        style P1 fill:#fff9c4,stroke:#fbc02d,stroke-width:2px
        style B1 fill:#c8e6c9,stroke:#388e3c,stroke-width:2px
        style A2 fill:#ffebee,stroke:#e53935
        style P2 fill:#fffde7,stroke:#fbc02d
        style B2 fill:#e8f5e9,stroke:#388e3c
    end
```

## Pipeline Stages

| Stage | Skill | Input | Output | Description |
|-------|-------|-------|--------|-------------|
| 1 | skill-architect | User Requirements | design.md | Design architecture |
| 2 | skill-planner | design.md | todo.md | Create implementation plan |
| 3 | skill-builder | design.md + todo.md | Skill Files | Build the skill |

## Handoff Contracts

### Architect → Planner
- §2 Capability Map → Planner audit 3 Tiers
- §3 Zone Mapping → Planner decompose thành Tasks
- §7 Progressive Disclosure Plan → Planner + Builder biết Tier 1/2 files
- §8 Risks → Builder tham chiếu khi Guardrails

### Planner → Builder
- §1 Pre-requisites → Builder chuẩn bị tài nguyên
- §2 Phase Breakdown → Builder execution plan
- §3 Knowledge & Resources → Builder reference
- §4 Definition of Done → Builder completion criteria

---

*For more details, see skill-architect/SKILL.md*
"""

    return diagram.format(date=datetime.now().strftime("%Y-%m-%d %H:%M"))


def main():
    output_file = None

    # Parse arguments
    args = sys.argv[1:]
    if "--output" in args:
        idx = args.index("--output")
        if idx + 1 < len(args):
            output_file = args[idx + 1]

    diagram = generate_pipeline_diagram()

    if output_file:
        Path(output_file).write_text(diagram, encoding="utf-8")
        print(f"✅ Pipeline diagram exported to: {output_file}")
    else:
        print(diagram)

    return 0


if __name__ == "__main__":
    sys.exit(main())
